theme: jekyll-theme-leap-day


    padding: 25px 20px 40px 20px;
    margin: 0;
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    width: 100%;
    text-align: center;
    background: url(./images/background.png) #000000e6;
    box-shadow: 1px 0px 2px rgb(0 0 0 / 75%);
    z-index: 99;
    -webkit-font-smoothing: antialiased;
    min-height: 76px;

    z-index: 100;
    left: 0;
    right: 50%;
    height: 50px;
    margin-right: -382px;
    position: fixed;
    top: 115px;
    background: #ffcc00;
    border: 1px solid #f0b500;
    box-shadow: 0px 1px 3px rgb(0 0 0 / 25%);
    border-radius: 0px 2px 2px 0px;
    padding-right: 10px;
